language: node_js
node_js:
  - node
warnings_are_errors: false
install:
  - npm install firebase-tools -g
script:
  - npm run build
  - firebase deploy --only hosting --token $FIREBASE_TOKEN
branches:
  only:
    - main
